CC  = gcc

CFLAGS = -Wall -O3
CC_LDFLAGS = 
INSTALL = install

####### Build rules

motion-jpg-fetch : motion-jpg-fetch.c
	$(CC) $(CFLAGS) motion-jpg-fetch.c -o motion-jpg-fetch $(CC_LDFLAGS)

clean:
	rm motion-jpg-fetch
	
